.git/
.git
.venv/
.venv
venv/
env/
__pycache__/
*.pyc
.pytest_cache/

IIMT30k_Vi/
IIMT30k_Vi.zip
outputs/
results/
tb/
logs/
cleaning/
docs/

vendor/*
!vendor/paddlex/
vendor/paddlex/*
!vendor/paddlex/official_models/
!vendor/paddlex/official_models/**

models/*
!models/mt-nllb-1p3b-en-vi/
models/mt-nllb-1p3b-en-vi/*
!models/mt-nllb-1p3b-en-vi/best/
!models/mt-nllb-1p3b-en-vi/best/**
